<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Fulfillment\Enums;

class TaxTypeEnum
{
    const C_GST                        = 'GST';
    const C_PROVINCE_SALES_TAX         = 'PROVINCE_SALES_TAX';
    const C_REGION                     = 'REGION';
    const C_STATE_SALES_TAX            = 'STATE_SALES_TAX';
    const C_VAT                        = 'VAT';
    const C_WHITE_GOODS_DISPOSABLE_TAX = 'WHITE_GOODS_DISPOSABLE_TAX';
    const C_ELECTRONIC_RECYCLING_FEE   = 'ELECTRONIC_RECYCLING_FEE';
    const C_MATTRESS_RECYCLING_FEE     = 'MATTRESS_RECYCLING_FEE';
    const C_ADDITIONAL_FEE             = 'ADDITIONAL_FEE';
    const C_BATTERY_RECYCLING_FEE      = 'BATTERY_RECYCLING_FEE';
    const C_TIRE_RECYCLING_FEE         = 'TIRE_RECYCLING_FEE';
}
