<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Fulfillment\Enums;

class VatTaxTypeEnum
{
    const C_ABN   = 'ABN';
    const C_IOSS  = 'IOSS';
    const C_IRD   = 'IRD';
    const C_OSS   = 'OSS';
    const C_VOEC  = 'VOEC';
}
