<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class ReturnShippingCostType
{
    const C_INSURANCE = 'INSURANCE';
    const C_LABEL_COST = 'LABEL_COST';
    const C_OTHER = 'OTHER';
    const C_SIGNATURE_CONFIRMATION_COST = 'SIGNATURE_CONFIRMATION_COST';
}
